# this file will be read by Catwatch
# see https://github.com/zalando/catwatch/issues/32
title: Connexion
# TODO: find proper image for Connexion
image: https://prismic-io.s3.amazonaws.com/zalando-jobsite/f4bd3629c63127c9a55ebe5ccb65b2de1e42e7c8_swagger.png
