ci:
  autoupdate_branch: "main"
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: "^connexion/"
        additional_dependencies:
          - flake8-rst-docstrings==0.2.3

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort
        files: "^connexion/"
        args: ["--project", "connexion", "--check-only", "--diff"]
      - id: isort
        name: isort examples
        files: "^examples/"
        args: ["--thirdparty", "connexion", "--check-only", "--diff"]
      - id: isort
        name: isort tests
        files: "^tests/"
        args: ["--project", "conftest", "--thirdparty", "connexion", "--check-only", "--diff"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        files: "^connexion/"
        args: ["connexion"]
      - id: black
        name: black examples
        files: "^examples/"
        args: ["examples"]
      - id: black
        name: black tests
        files: "^tests/"
        args: ["tests"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        files: "^connexion/"
        args: ["--ignore-missing-imports", "connexion"]
        additional_dependencies:
          - types-jsonschema
          - types-PyYAML
          - types-requests
        pass_filenames: false
