swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /swagger

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      operationId: app.post_greeting
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
        - name: body
          in: body
          description: >
            Optional body with a message.
            Send message "crash" or "invalid" to simulate an error.
          schema:
            type: object
            properties:
              message:
                type: string
                example: "hi"
      produces:
        - application/json
      responses:
        '200':
          description: greeting response
          schema:
            type: object
            properties:
              greeting:
                type: string
            required:
              - greeting
            example:
              greeting: "Hello John"
