name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black codespell flake8 isort mypy pytest pyupgrade safety
      - run: black --check . || true
      - run: codespell --ignore-words-list="connexion"
      - run: flake8 . --count --select=E9,F63 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=19 --max-line-length=166 --show-source --statistics
      - run: isort --check-only --profile black . || true  # PR #1384
      - run: ./setup.py --help
      - run: ./setup.py install
      - run: ./setup.py test
      - run: pip install -e .[swagger-ui]
      - run: pip install aiohttp aiohttp_jinja2 aiohttp_remotes pytest-aiohttp
      - run: mypy --ignore-missing-imports . || true
      - run: pytest .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
