name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black codespell flake8 isort mypy pytest pyupgrade safety
      - run: black --check . || true
      - run: codespell --ignore-words-list="connexion" || true  # --skip=""
      - run: flake8 . --count --select=E9,F63 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
      #- run: ./setup.py flake8
      - run: isort --check-only --profile black . || true
      - run: ./setup.py --help
      - run: ./setup.py install
      - run: pip install aiohttp aiohttp_jinja2 aiohttp_remotes pip install pytest-aiohttp-client
      #- run: pip install -r requirements.txt || true
      #- run: pip install -e .
      - run: mypy --ignore-missing-imports . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
